### ISSUE TITLE
Readme is apocryphal

### ISSUE THREAD

**Issue by evansolomon** [tollmanz/ostrichcize#11]
> Contrary to popular belief, ostriches do not bury their heads in sand to avoid danger

— [Citation added](https://en.wikipedia.org/wiki/Ostrich#Behaviour_and_ecology)

**Comment by tollmanz** [comment]
I disagree. [Indisputable proof](https://www.google.com/search?q=ostrich+head+in+sand&source=lnms&tbm=isch&sa=X&ei=WVjnUZvlD8aTiQKE-YHYBg&ved=0CAcQ_AUoATgK&biw=1216&bih=695).

**Comment by markjaquith** [comment]
I heard that touching toads will give me warts. Is this true? Please answer in the form of a software project.

**Comment by robertdall** [comment]
I heard watching sharknado reduces your IQ can you please provide examples in your software project suggested above.

**Comment by markjaquith** [comment]
I require that they be separate projects, in case your sharknado might contract warts by being bundled into my project.

**Comment by aaronjorbin** [comment]
Please call the editor of the New York Times and tell them that Qaddhafi is spelled with an h and two ds and isn't a seven letter word for anything

**Comment by andrewspittle** [comment]
I heard writing on Medium places you in touch with the spirit world. @evansolomon, can you confirm?

**Comment by evansolomon** [comment]
@andrewspittle I'm not sure. I just invited you to write on Medium, so let me know what you decide.

**Comment by tollmanz** [comment]
@markjaquith [Frog CMS](http://www.madebyfrog.com/) is a thing. It has [vulnerabilities](http://forums.cnet.com/7726-6132_102-5033186.html), which could lead to a virus. [Viruses cause warts](http://www.mayoclinic.org/medical-edge-newspaper-2011/may-20b.html). It is possible that with the right virus, Frog CMS can give you warts.

**Comment by benbalter** [comment]
Not sure if this is the right place, but I'm still having trouble accessing Admin Back Office. WHY WON'T YOU HELP ME!?!

This is all I get:

![admin-back-office](https://f.cloud.github.com/assets/282759/816971/59e86980-ef5f-11e2-90e6-c648dc626235.gif)

/cc @nacin

**Comment by tollmanz** [comment]
@robertdall As part of the WordPress class I am teaching, I wrote a [Sharknado Relief campaign plugin](https://github.com/tollmanz/wordpress-development-course/blob/master/slides/hooks.html#L208-214) as an example. If we can rid the world of Sharknado, we can avoid a shark-wart pandemic?!?

**Comment by evansolomon** [comment]
So are you going to fix that ostrich thing?

**Comment by markjaquith** [comment]
@evansolomon right now:

![screen shot 2013-07-18 at 3 16 28 am](https://f.cloud.github.com/assets/353790/817624/0969993c-ef7a-11e2-95e2-0642dce93164.png)

@tollmanz right now:

![funny-gif-ostrich-ski](https://f.cloud.github.com/assets/353790/817633/85a7e288-ef7a-11e2-9e57-3ad01b4f36f4.gif)

**Comment by ghost** [comment]
I guess I'm just confused why you cited Wikipedia instead of using the actual citation from there. 

[Citation](http://nature.ca/notebooks/english/ostrich.htm)

**Comment by tollmanz** [comment]
@ryanduff Thanks for pointing that out! @evansolomon's work is clearly subpar here. I will accept a PR if you up your game a bit, @evansolomon.

**Comment by aaronjorbin** [comment]
Why is this bug still outstanding? Won't someone please fix it.

**Comment by tollmanz** [comment]
...and I am just itchin' to merge a PR.

**Comment by ghost** [comment]
I think the lack of traction is because everyone stuck their head in the sand.
