### ISSUE TITLE
Slashes depend on settings

### ISSUE THREAD

**Issue by franz-josef-kaiser** [tollmanz/ostrichcize#6]
Not every blog has a trailing slash, like used [here](https://github.com/tollmanz/ostrichcize/blob/master/ostrichcize.php#L120).

```
$paths[] = user_trailingslashit( trailingslashit( $dir ) . $slug );
```

`user_trailingslashit()` considers that fact.

**Comment by tollmanz** [comment]
The trailing slash is not added to the end of a URL. It is added to a path of a plugin. For instance, it changes: `/Users/me/Sites/my-site/wp-content/plugins/buddypress` to `/Users/me/Sites/my-site/wp-content/plugins/buddypress/`. The reason I elected to add the slash is to ensure that incorrect plugins are not ostrichcized. For instance, without the slash, a buddypress plugin that has the following path may be silenced: `/Users/me/Sites/my-site/wp-content/plugins/buddypress-like-button`. I think the slash is necessary and thus I'm closing the issue for now.
